### ISSUE TITLE
Broken at least figure, table and example numbering in docx, odt, epub with latest pandoc 2.17.1.1 inside RStudio 2022.02.0 Build 443

### ISSUE THREAD

**Issue by N0rbert** [rstudio/bookdown#1313]
Below is the minimal reproducible example (`index.Rmd` file):

<pre>

---
title: Figures, tables and listings numbering issue
documentclass: book
site: bookdown::bookdown_site
output:
  bookdown::html_document2: default
  bookdown::word_document2: default
  bookdown::epub_book: default
  bookdown::odt_document2: default
---

```{r eval=TRUE, include=TRUE}
sessionInfo('bookdown')
rmarkdown::pandoc_version()
```

# Zero 1 {-#zero1}

Some text in 1st unnumbered section.

# Practically long header about some theories {#theory}

## Markdown Syntax {#markdown-syntax}

...

### Images {#markdown-syntax-media}

First figure of first section is below, it reference is Fig. \@ref(fig:md-logo).

![(\#fig:md-logo) Markdown logo](https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Markdown-mark.svg/208px-Markdown-mark.svg.png)

...

### Tables {#markdown-syntax-tables}

Below is table with reference - see Table \@ref(tab:my-tab).

Table: (\#tab:my-tab) My table caption

| **Column 1** | **Column 2** |
|--------------|--------------|
| Text         | Text         |

### Equations {#markdown-syntax-math}

Binom is below, it is labeled as \@ref(eq:binom):

\begin{equation}
f\left(k\right) =\binom{n}{k} p^k\left(1-p\right)^{n k}
(\#eq:binom)
\end{equation}

### Source code listings {#markdown-listings}

...

Numbered example is below, it is numbered as Example \@ref(exm:exm-my):

```{example, exm-my}
My example
```
```
int main(){
  return 0;
}
```

...

# Practice {#chapter2}

...

# Conclusion {-#conclusion}

...

# References {-#references}

...
</pre>

While knitting this document using RStudio 2022.02.0 Build 443 with integrated latest pandoc 2.17.1.1 to HTML I get correct rendering 

![html-ok](https://user-images.githubusercontent.com/309456/155849009-a6ac3d68-a1ff-4822-ba87-98d55c247c3a.png)

but in docx, odt and epub all figure, table and example numbers are starting from zero, see odt as example below:

![odt-wrong](https://user-images.githubusercontent.com/309456/155849052-b88c7e14-43fb-4fec-9e64-c38ef0f53d3b.png)

It is Ubuntu MATE 18.04.6 LTS. Other details:

```
sessionInfo('bookdown')
## R version 3.4.4 (2018-03-15)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 18.04.6 LTS
## 
## Matrix products: default
## BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
## LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
## 
## locale: C
## 
## attached base packages:
## character(0)
## 
## other attached packages:
## [1] bookdown_0.24
## 
## loaded via a namespace (and not attached):
##  [1] compiler_3.4.4  magrittr_2.0.2  fastmap_1.1.0   cli_3.2.0      
##  [5] graphics_3.4.4  tools_3.4.4     htmltools_0.5.2 rstudioapi_0.13
##  [9] utils_3.4.4     yaml_2.3.5      grDevices_3.4.4 stats_3.4.4    
## [13] datasets_3.4.4  stringi_1.7.6   rmarkdown_2.11  knitr_1.37     
## [17] methods_3.4.4   stringr_1.4.0   xfun_0.29       digest_0.6.29  
## [21] rlang_1.0.1     base_3.4.4      evaluate_0.15
rmarkdown::pandoc_version()
## [1] '2.17.1.1'
```

Note: I tried to run `remotes::install_github("rstudio/bookdown")` but with it I can't Knit the document with the following error:

```
Error in pandoc_math_engines() : 
  could not find function "pandoc_math_engines"
Calls: <Anonymous> ... add_math_support -> pandoc_math_args -> match.arg -> eval -> eval
Please delete _main.Rmd after you finish debugging the error.
Execution halted
```

So I'm staying with latest stable versions.

**Comment by cderv** [comment]
> Note: I tried to run remotes::install_github("rstudio/bookdown") but with it I can't Knit the document with the following error:
> ```
> Error in pandoc_math_engines() : 
>  could not find function "pandoc_math_engines"
> ```

`pandoc_math_engines()` is a new internal function from dev rmarkdown. When you install dev bookdown, it should correctly install dev rmarkdown. However, if you have currently a rmarkdown version loaded, maybe this conflicts. You should try installing from a fresh session. If that still not work , there is definitely something to look into. 

On my side, installing dev bookdown works, and with this version I can't reproduce this issue. I can with CRAN versions of package, so it should have been fixed in the recent PR for Pandoc 2.17 compatibility. 

<details>
<summary>Session Info</summary>

````r
> sessioninfo::package_info(c("bookdown"))
 package   * version date (UTC) lib source
 base64enc   0.1-3   2015-07-28 [1] CRAN (R 4.1.0)
 bookdown    0.24.10 2022-02-28 [1] Github (rstudio/bookdown@5f891ee)
 bslib       0.3.1   2021-10-06 [1] CRAN (R 4.1.1)
 digest      0.6.29  2021-12-01 [1] CRAN (R 4.1.1)
 evaluate    0.14    2019-05-28 [1] CRAN (R 4.1.0)
 fastmap     1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
 fs          1.5.2   2021-12-08 [1] CRAN (R 4.1.2)
 glue        1.6.1   2022-01-22 [1] CRAN (R 4.1.2)
 highr       0.9     2021-04-16 [1] CRAN (R 4.1.0)
 htmltools   0.5.2   2021-08-25 [1] CRAN (R 4.1.1)
 jquerylib   0.1.4   2021-04-26 [1] CRAN (R 4.1.0)
 jsonlite    1.7.3   2022-01-17 [1] CRAN (R 4.1.2)
 knitr       1.37    2021-12-16 [1] CRAN (R 4.1.2)
 magrittr    2.0.2   2022-01-26 [1] CRAN (R 4.1.2)
 R6          2.5.1   2021-08-19 [1] CRAN (R 4.1.1)
 rappdirs    0.3.3   2021-01-31 [1] CRAN (R 4.1.0)
 rlang       1.0.1   2022-02-03 [1] CRAN (R 4.1.2)
 rmarkdown   2.11.22 2022-02-28 [1] Github (rstudio/rmarkdown@1c05487)
 sass        0.4.0   2021-05-12 [1] CRAN (R 4.1.0)
 stringi     1.7.6   2021-11-29 [1] CRAN (R 4.1.1)
 stringr     1.4.0   2019-02-10 [1] CRAN (R 4.1.0)
 tinytex     0.36    2021-12-19 [1] CRAN (R 4.1.1)
 xfun        0.29    2021-12-14 [1] CRAN (R 4.1.2)
 yaml        2.2.2   2022-01-25 [1] CRAN (R 4.1.2)

 [1] C:/Users/chris/Documents/R/win-library/4.1
 [2] C:/Program Files/R/R-4.1.2/library
````

</details>

**Comment by N0rbert** [comment]
The dev version works normally after cleaning `~/R` folder. Thanks!

**Comment by cderv** [comment]
Great ! 

We will make a release to CRAN very soon. 

I'll close this then.

**Comment by cderv** [comment]
Thanks again for reporting. I can reproduce. We may have missed something. Sorry for the trouble

**Comment by cderv** [comment]
I believe this is a new issue - very recent as due to a 2 days ago commit https://github.com/rstudio/bookdown/commit/ddca7bb83ba32fd03dea929a8af5cb49b742d564 in order to fix https://github.com/rstudio/bookdown/issues/1178
We decided to switch the engine syntax to use the custom block syntax: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems to fix the issue for PDF output. 
However, this has been done unconditionally and fenced div syntax is working only with HTML and PDF output. 
That explain why this is broken, but that is no good for you. 

@yihui we may have not completely consider all the usage - HTML and PDF are the main focus of **bookdown** for sure but for user playing with other format, last **bookdown** has broke the custom environment feature. We need to think through this.

**Comment by yihui** [comment]
I'll make it conditional soon.

**Comment by yihui** [comment]
Done. You can install the development version via

```r
remotes::install_github('rstudio/bookdown')
```

Thanks!

**Comment by N0rbert** [comment]
It does not work with `remotes::install_github('rstudio/bookdown')`. I still get 

```
Warning message:
The label(s) exm:exm-my not found 
```

It happens on 

```
$ rstudio --version
2022.02.0+443

> sessionInfo('bookdown')
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
[1] C

attached base packages:
character(0)

other attached packages:
[1] bookdown_0.25.2

loaded via a namespace (and not attached):
[1] compiler_3.4.4  graphics_3.4.4  utils_3.4.4     grDevices_3.4.4
[5] stats_3.4.4     datasets_3.4.4  methods_3.4.4   base_3.4.4     

> rmarkdown::pandoc_version()
[1] '2.17.1.1'

```

**Comment by yihui** [comment]
Sorry, please reinstall the dev version. I just pushed a fix and tested it. Should be working now. Thanks!

**Comment by N0rbert** [comment]
Still does not work.

I'm automating this using commands below:

    mkdir -p ~/Documents/R/bookdown-issue-1313
    cd ~/Documents/R/bookdown-issue-1313
    cat <<\EOF > index.Rmd

    ---
    title: Figures, tables and listings numbering issue
    documentclass: book
    site: bookdown::bookdown_site
    output:
    bookdown::html_document2: default
    bookdown::word_document2: default
    bookdown::epub_book: default
    bookdown::odt_document2: default
    ---

    ```{r eval=TRUE, include=TRUE}
    sessionInfo('bookdown')
    rmarkdown::pandoc_version()
    ```

    # Zero 1 {-#zero1}

    Some text in 1st unnumbered section.

    # Practically long header about some theories {#theory}

    ## Markdown Syntax {#markdown-syntax}

    ...

    ### Images {#markdown-syntax-media}

    First figure of first section is below, it reference is Fig. \@ref(fig:md-logo).

    ![(\#fig:md-logo) Markdown logo](https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Markdown-mark.svg/208px-Markdown-mark.svg.png)

    ...

    ### Tables {#markdown-syntax-tables}

    Below is table with reference - see Table \@ref(tab:my-tab).

    Table: (\#tab:my-tab) My table caption

    | **Column 1** | **Column 2** |
    |--------------|--------------|
    | Text         | Text         |

    ### Equations {#markdown-syntax-math}

    Binom is below, it is labeled as \@ref(eq:binom):

    \begin{equation}
    f\left(k\right) =\binom{n}{k} p^k\left(1-p\right)^{n k}
    (\#eq:binom)
    \end{equation}

    ### Source code listings {#markdown-listings}

    ...

    Numbered example is below, it is numbered as Example \@ref(exm:exm-my):

    ```{example, exm-my}
    My example
    ```
    ```
    int main(){
    return 0;
    }
    ```

    ...

    # Practice {#chapter2}

    ...

    # Conclusion {-#conclusion}

    ...

    # References {-#references}

    ...
    EOF


Then I have a script:

```
cat <<EOF > _build.sh
#!/bin/sh
set -ev

export DEBIAN_FRONTEND=noninteractive

echo 'Acquire::http::Proxy "http://192.168.3.222:8000";' > /etc/apt/apt.conf.d/99proxy

apt-get update && \
apt-get dist-upgrade -y && \
apt-get install -y r-base-dev wget

cd /root
wget -c https://github.com/jgm/pandoc/releases/download/2.16.1/pandoc-2.16.1-1-amd64.deb
apt-get install -y ./pandoc-2.16.1-1-amd64.deb

Rscript -e "install.packages('remotes')"
Rscript -e "remotes::install_github('rstudio/bookdown')"

Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::word_document2')"
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::odt_document2')"

EOF
```

Run:

```
docker run -it --rm -v $(pwd):/root ubuntu:bionic bash /root/_build.sh
```

Results with stable pandoc 2.16.1:

* *bionic* with R 3.4.4 - FAIL
* *focal* with R 3.6.3 - FAIL
* *impish* with R 4.0.4 - FAIL
* *jammy* with R 4.1.2 - TODO

In the above list by FAIL I mean having `Warning message:`  
`The label(s) exm:exm-my not found`.

**Comment by cderv** [comment]
I think odt output is sill missing the tweaks. For `epub_book` and `word_document2` is should be ok in your test.

**Comment by cderv** [comment]
The last commit should correctly detect `odt_document2()` and bring back support. I tested with you initial example above in first post.

**Comment by N0rbert** [comment]
Thanks, but while running below commands (to have latest Pandoc 2.17.1.1):

```
cd ~/Documents/R/bookdown-issue-1313
sed -i "s/2.16.1/2.17.1.1/g" _build.sh
```

I still get single problem with *epub*:

```
$ docker run -it --rm -v $(pwd):/root ubuntu:bionic bash /root/_build.sh | grep -A1 "Warning message:" -B2
Output created: _book/_main.epub
[1] "/root/_book/_main.epub"
Warning message:
The label(s) exm:exm-my not found 
```

So please finally fix a problem with EPUB output.

**Comment by cderv** [comment]
EPUB should now work. 

Thanks a lot for all your testing and sorry for all the back and forth on this one.

**Comment by N0rbert** [comment]
Thanks, now all formats look good.
