### ISSUE TITLE
Referencing sections with \@ref do not work with word_document2

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#239]
Hi, 

I notice in #191 that cross-referencing with figures have been fixed but I encounter an issue to reference section with `\@ref(label)` and rendering into `word_document2`

As example, I use the bookdown-demo project. In `_output.yml`, I add `bookdown::word_document2: default`, then not modifying anything else I build the work_document2 book in Rstudio with the build panel.

There are warnings : 
```r
The label(s) intro, methods not found
```
These lines in `01-intro.Rmd`:
```
# Introduction {#intro}

You can label chapter and section titles using `{#label}` after them, e.g., 
we can reference Chapter \@ref(intro). If you do not manually label them,
 there will be automatic labels anyway, e.g., Chapter 
\@ref(methods).
```
do not render properly as there are `??` into the word document
```
Introduction
You can label chapter and section titles using {#label} after them, 
e.g., we can reference Chapter ??. If you do not manually label them, 
there will be automatic labels anyway, e.g., Chapter ??.
```

However, Figure and table referencing are working as `\@ref(tab:nice-tab)` and `\@ref(fig:nice-fig)` are rendering well.

am I doing something wrong or is there still an issue ?

**Comment by yihui** [comment]
Thanks for the report! I don't have Word to test it right now, but I just pushed a blind fix.

**Comment by cderv** [comment]
I can confirm it is working now. Thanks!

**Comment by IgorFobia** [comment]
I still have this problem; it is also on this document available online:
https://rdrr.io/github/rstudio/bookdown/f/inst/examples/02-components.Rmd
