### ISSUE TITLE
Problem with publish_book()

### ISSUE THREAD

**Issue by Nowosad** [rstudio/bookdown#68]
When I tried `bookdown::publish_book()` for the first time, I authorized `bookdown` to publish to bookdown.org account. However, afterwards I got an error: 
```
Error in rsconnect::deploySite(siteDir = getwd(), siteName = name, account = account,  : 
  index file with site entry not found in name_of_my_directory
```

Now, everytime I try to use `bookdown::publish_book()`, I've got that error.

**Comment by yihui** [comment]
Could you try `devtools::install_github('rstudio/bookdown')` again? (it may reinstall the dev versions of rmarkdown and rsconnect, which might fix your issue)

**Comment by jjallaire** [comment]
Yes, I think if you update bookdown this should be resolved. Let us know if
it's not!

**Comment by jjallaire** [comment]
Note that's update bookdown with devtools >= 1.10 (which will cause the
updating of rmarkdown and rsconnect, which as Yihui said is likely where
the fix will be found)

**Comment by Nowosad** [comment]
Thanks for the help. However, it didn't solve the problem. I'm on Ubuntu 14.04 using RStudio version 0.99.1119. I've installed `devtools` (version 1.10.0.9000)   and `bookdown` (version 0.0.60):
```
devtools::install_github("hadley/devtools")
devtools::install_github('rstudio/bookdown')
```
Afterwards I've tried to use `bookdown::publish_book()`:

```
bookdown::publish_book()
You do not currently have a bookdown.org publishing account configured on this system.
Would you like to configure one now? [Y/n]: Y
A browser window should open; if it doesn't, you may authenticate manually by visiting https://bookdown.org/__login__?url=here_is_url_address.
Waiting for authentication...
Account registered successfully: nowosad
Error in rsconnect::deploySite(siteDir = getwd(), siteName = name, account = account,  : 
  index file with site entry not found in *name_of_my_directory*
```

**Comment by Nowosad** [comment]
I've decide to try if https://github.com/rstudio/bookdown-demo is going to work, instead of my book. I've download the repo. And I've used `bookdown::publish_book()
`:
```
bookdown::publish_book()
Error in deployApp(appName = appName, appDir = appDir, appFiles = appFiles,  : 
  _book does not exist
```
So I've build the site, and afterwards:

```
bookdown::publish_book()
Preparing to deploy site...DONE
Uploading bundle for site: 18...DONE
Deploying bundle: 75 for site: 18 ...
Deploying static content
Site successfully deployed to my_address

```

Therefore, the problem is probably with my bookdown files. But I have no clue what is exactly wrong.

**Comment by Nowosad** [comment]
Problem solved! I've looked for the differences between my bookdown files and bookdown-demo files - the solution to the problem was to add `site: bookdown::bookdown_site` in the YAML of index.Rmd file.
Thanks for great work @yihui @jjallaire

**Comment by jjallaire** [comment]
Sorry the way of "declaring" a site has been moving around quite a bit the
past few days, glad you got it sorted out!
