### ISSUE TITLE
.unlisted class not suppressing in table of contents

### ISSUE THREAD

**Issue by wjakethompson** [rstudio/bookdown#894]
This is cross-posted from [StackOverflow](https://stackoverflow.com/questions/62093984/suppress-r-markdown-heading-from-toc). I have a bookdown project where I would like to exclude a heading from the table of contents. From https://github.com/rstudio/rmarkdown/issues/1625#issuecomment-558854773, and the [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/toc-unlisted.html), it appears this should be possible by adding the unlisted and unnumbered classes, e.g.,

```
# Section heading {.unlisted .unnumbered}
```

However, when I apply these classes, only the unnumbered seems to have an effect. That is, the section heading still appears in the TOC, but without a number (i.e., the same effect as `# Section heading {-}`).

A minimal example is in [this repo](https://github.com/wjakethompson/bd-reprex), and the rendered book [here](https://bd-reprex.netlify.app/). I have also tried with a standard `rmarkdown::html_document()` output ([repo](https://github.com/wjakethompson/rmd-reprex) and [rendered site](https://wjakethompson.github.io/rmd-reprex/index.html)), but that doesn't appear to render correctly either.

```r
rmarkdown::pandoc_version()
#> [1] '2.9.2.1'

xfun::session_info()
#> R version 4.0.0 (2020-04-24)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Mojave 10.14.6, RStudio 1.3.952
#> 
#> Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8
#> 
#> Package version:
#>   askpass_1.1       assertthat_0.2.1  backports_1.1.7   base64enc_0.1.3  
#>   BH_1.72.0.3       bookdown_0.19.1   brew_1.0.6        callr_3.4.3      
#>   cli_2.0.2         clipr_0.7.0       commonmark_1.7    compiler_4.0.0   
#>   covr_3.5.0        crayon_1.3.4      crosstalk_1.1.0.1 curl_4.3         
#>   desc_1.2.0        devtools_2.3.0    digest_0.6.25     DT_0.13          
#>   ellipsis_0.3.1    evaluate_0.14     fansi_0.4.1       fs_1.4.1         
#>   gh_1.1.0          git2r_0.27.1      glue_1.4.1        graphics_4.0.0   
#>   grDevices_4.0.0   highr_0.8         htmltools_0.4.0   htmlwidgets_1.5.1
#>   httr_1.4.1        ini_0.3.1         jsonlite_1.6.1    knitr_1.28       
#>   later_1.0.0       lazyeval_0.2.2    lifecycle_0.2.0   magrittr_1.5     
#>   markdown_1.1      memoise_1.1.0     methods_4.0.0     mime_0.9         
#>   openssl_1.4.1     packrat_0.5.0     pillar_1.4.4      pkgbuild_1.0.8   
#>   pkgconfig_2.0.3   pkgload_1.1.0     praise_1.0.0      prettyunits_1.1.1
#>   processx_3.4.2    promises_1.1.0    ps_1.3.3          purrr_0.3.4      
#>   R6_2.4.1          rcmdcheck_1.3.3   Rcpp_1.0.4.6      rematch2_2.1.2   
#>   remotes_2.1.1     rex_1.2.0         rlang_0.4.6       rmarkdown_2.1.10 
#>   roxygen2_7.1.0    rprojroot_1.3-2   rstudioapi_0.11   rversions_2.0.2  
#>   sessioninfo_1.1.1 stats_4.0.0       stringi_1.4.6     stringr_1.4.0    
#>   sys_3.3           testthat_2.3.2    tibble_3.0.1      tinytex_0.23     
#>   tools_4.0.0       usethis_1.6.1     utf8_1.1.4        utils_4.0.0      
#>   vctrs_0.3.0       whisker_0.4       withr_2.2.0       xfun_0.14        
#>   xml2_1.3.2        xopen_1.0.0       yaml_2.2.1       
```
<sup>Created on 2020-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
I think this is related to a bug in pandoc  See https://github.com/jgm/pandoc/issues/6339
Currently, it seems you need to use `number_sections: false` to exclude to title from the TOC. 

Next pandoc version should fix this and this feature will then need the last pandoc version to work after.

**Comment by wjakethompson** [comment]
I've upgraded to [Pandoc 2.10](https://github.com/jgm/pandoc/releases/tag/2.10) locally, and everything is working as expected! The remote builds are still showing the old behaviors, but this appears to be because Homebrew still has version 2.9.2.1. Presumably, the Homebrew formula will get updated eventually and then the remote builds will also work!

Thanks!

**Comment by OliBravo** [comment]
Hi,
I upgraded to Pandoc 2.11.3.1 from 2.9. Applying the class {.unlisted} not working. My section header is still visible in the TOC.
I use:

```
output: 
  html_document:
    theme: spacelab
    toc: yes
    toc_float: yes
    df_print: paged
    number_sections: false
```

and then

```
# Omit this {.unlisted .unnumbered}
```

**Comment by atusy** [comment]
@OliBravo

I find the issue arises when `toc_float: true`, and made a PR to fix it (#1993)

BTW, I recommend opening a new issue instead of commenting an old (solved) issue because more people will catch it.

**Comment by OliBravo** [comment]
@atusy Thanks, sorry for commenting on the closed issue. I'm looking forward to the update.
