### ISSUE TITLE
Invalid JSON in search_index.json silently breaks the search bar

### ISSUE THREAD

**Issue by wlandau** [rstudio/bookdown#913]
## Prework

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('bookdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/bookdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

## Issue

Problems with `search_index.json` seem to break the search bar. For example, in https://github.com/ShKlinkenberg/Interactive_Teaching_Techniques/commit/f80156e0d2bd0df018e5126987732aff73223b00, because of an unusual character at the beginning of [this line](https://github.com/ShKlinkenberg/Interactive_Teaching_Techniques/blob/f80156e0d2bd0df018e5126987732aff73223b00/17-Interaction_Through_Homewor.Rmd#L38), [the site's `search_index.json`](https://github.com/ShKlinkenberg/Interactive_Teaching_Techniques/blob/f80156e0d2bd0df018e5126987732aff73223b00/docs/search_index.json) contains invalid JSON (according to https://jsonlint.com). When I launch the book with `bookdown::serve_book()` and click the search icon, the search text box does not appear. But after I delete the strange character and render the book again, the search bar starts working (see https://github.com/ShKlinkenberg/Interactive_Teaching_Techniques/pull/4). https://github.com/ropensci-books/drake/issues/165 is an instance of the same problem with the same solution, and I suspect https://github.com/rstudio/bookdown-demo/issues/12, https://github.com/rstudio/bookdown/issues/290, and https://github.com/rstudio/bookdown/issues/791 are also related.

**Comment by yihui** [comment]
Should be fixed now. Thanks a lot for the report and debugging!

**Comment by wlandau** [comment]
Glad it helped!

Unfortunately, I am still experiencing the same problem when I call `serve_book()` using https://github.com/rstudio/bookdown/commit/31f3197e66cd0ced252dfccf50067ec12f4fabb9 to render  https://github.com/ShKlinkenberg/Interactive_Teaching_Techniques/commit/f80156e0d2bd0df018e5126987732aff73223b00. Here is the full `search_index.json`, which still does not validate with [JSONLint](https://jsonlint.com).

```json
[
["index.html", "Interactive Teaching Techniques Chapter 1 Introduction 1.1 Interactive Teaching Techniques 1.2 Chapters", " Interactive Teaching Techniques Teaching &amp; Learning Centre 2020-07-24 Chapter 1 Introduction Welcome to the ebook on interactive teaching techniques. This document is based on the Interactive Techniques PDF of Kevin Yee. Based on the creative commons licence the Teaching &amp; Learning Centre of the University of Amsterdam is maintaining and expanding this ebook version. The full credits can be found at the end of this ebook. 1.1 Interactive Teaching Techniques These techniques presented in this ebook have multiple benefits: the instructor can easily and quickly assess if students have really mastered the material (and plan to dedicate more time to it, if necessary), and the process of measuring student understanding in many cases is also practice for the material—often students do not actually learn the material until asked to make use of it in assessments such as these. Finally, the very nature of these assessments drives interactivity and brings several benefits. Students are revived from their passivity of merely listening to a lecture and instead become attentive and engaged, two prerequisites for effective learning. These techniques are often perceived as “fun”, yet they are frequently more effective than lectures at enabling student learning. Not all techniques listed here will have universal appeal, with factors such as your teaching style and personality influencing which choices may be right for you. 1.2 Chapters Instructor Action: Lecture Instructor Action: Lecture (Small Class Size) Student Action Individual Student Action: Pairs Student Action: Groups Second Chance Testing Authorized “Cheating” on In-Class Quizzes Testing Strategies YouTube Twitter Mobile and Tablet Devices Clickers, Student Responses, and Alternatives Creating Groups Icebreakers Games (Useful for Review) Interaction Through Homework Role-Play Student Presentations Brainstorming Online Interaction "],
["instructor-action-lecture.html", "Chapter 2 Instructor Action: Lecture 2.1 Picture Prompt 2.2 Why Do You Think That? 2.3 Think Break 2.4 Updating Notes 2.5 Cliffhanger Lecturing 2.6 Choral Response 2.7 Word Cloud Guessing 2.8 Instructor Storytelling 2.9 Grab a Volunteer 2.10 Socratic Questioning 2.11 Pass the Pointer 2.12 Turn My Back 2.13 Empty Outlines 2.14 Classroom Opinion Polls 2.15 Discussion Row 2.16 Total Physical Response (TPR) 2.17 Student Polling 2.18 Self-Assessment of Ways of Learning 2.19 Quote Minus One 2.20 Everyday Ethical Dilemmas 2.21 Polar Opposites 2.22 Pop Culture 2.23 Make Them Guess 2.24 Make It Personal 2.25 Read Aloud 2.26 Punctuated Lectures 2.27 Word of the Day 2.28 Recall, Summarize, Question, Connect, and Comment 2.29 Background Knowledge Probe 2.30 Goal Ranking and Matching 2.31 Interest/Knowledge/Skills Checklist 2.32 Documented Problem Solutions 2.33 Provocative Picture", " Chapter 2 Instructor Action: Lecture 2.1 Picture Prompt Show students an image with no explanation, and ask them to identify/explain it, and justify their answers. Or ask students to write about it using terms from lecture, or to name the processes and concepts shown. Also works well as group activity. Do not give the “answer” until they have explored all options first. 2.2 Why Do You Think That? Follow up all student responses (not just the incorrect ones) with a challenge to explain their thinking, which trains students over time to think in discipline-appropriate ways. 2.3 Think Break Ask a rhetorical question, and then allow 20 seconds for students to think about the problem before you go on to explain. This technique encourages students to take part in the problem-solving process even when discussion isn’t feasible. Having students write something down (while you write an answer also) helps assure that they will in fact work on the problem. 2.4 Updating Notes Take a break for 2-3 minutes to allow students to compare their class notes so far with other students, fill in gaps, and develop joint questions. 2.5 Cliffhanger Lecturing Rather than making each topic fit neatly within one day’s class period, intentionally structure topics to end three-fourths of the way through the time, leaving one quarter of the time to start the next module/topic. This generates an automatic bridge between sessions and better meets learning science principles of the spacing effect and interleaving topics. 2.6 Choral Response Ask a one-word answer to the class at large; volume of answer will suggest degree of comprehension. Very useful to “drill” new vocabulary words into students. 2.7 Word Cloud Guessing Before you introduce a new concept to students, show them a word cloud on that topic, using an online generator (Wordle, Taxedo, or Tagul) to paste a paragraph or longer of related text, and challenge students to guess what the topic was. 2.8 Instructor Storytelling Instructor illustrates a concept, idea, or principle with a real- life application, model, or case-study. 2.9 Grab a Volunteer After a minute paper (or better: think pair share) pick one student to stand up, cross the room, and read any other student’s answer. 2.10 Socratic Questioning The instructor replaces lecture by peppering students with questions, always asking the next question in a way that guides the conversation toward a learning outcome (or major Driving Question) that was desired from the beginning. Variation: A group of students writes a series of questions as homework and leads the exercise in class. Reverse Socratic Questioning The instructor requires students to ask him/her questions, and the instructor answers in such a way as to goad another question immediately but also drive the next student question in a certain direction. 2.11 Pass the Pointer Place a complex, intricate, or detailed image on the screen and ask for volunteers to temporarily borrow the laser pointer to identify key features or ask questions about items they don’t understand. 2.12 Turn My Back Face away from the class, ask for a show of hands for how many people did the reading. After they put hands down, turn around again and ask to hear a report of the percentage. This provides an indication of student preparation for today’s material. 2.13 Empty Outlines Distribute a partially completed outline of today’s lecture and ask students to fill it in. Useful at start or at end of class. 2.14 Classroom Opinion Polls Informal hand-raising suffices to test the waters before a controversial subject. 2.15 Discussion Row Students take turns sitting in a front row that can earn extra credit as individuals when they volunteer to answer questions posed in class; this provides a group that will ALWAYS be prepared and interact with teacher questions. 2.16 Total Physical Response (TPR) Students either stand or sit to indicate their binary answers, such as True/False, to the instructor’s questions. 2.17 Student Polling Select some students to travel the room, polling the others on a topic relevant to the course, then report back the results for everyone. 2.18 Self-Assessment of Ways of Learning Prepare a questionnaire for students that probes what kind of learning style they use, so the course can match visual/aural/tactile learning styles. 2.19 Quote Minus One Provide a quote relevant to your topic but leave out a crucial word and ask students to guess what it might be: “I cannot forecast to you the action of ______; it is a riddle, wrapped in a mystery, inside an enigma.” This engages them quickly in a topic and makes them feel invested. 2.20 Everyday Ethical Dilemmas Present an abbreviated case study with an ethical dilemma related to the discipline being studied. 2.21 Polar Opposites Ask the class to examine two written-out versions of a theory (or corollary, law of nature, etc.), where one is incorrect, such as the opposite or a negation of the other. In deciding which is correct, students will have to examine the problem from all angles. 2.22 Pop Culture Infuse your lectures, case studies, sample word problems for use during class with current events from the pop culture world. Rather than citing statistics for housing construction, for instance, illustrate the same statistical concept you are teaching by inventing statistics about something students gossip about, like how often a certain pop star appears in public without make-up. 2.23 Make Them Guess Introduce a new subject by asking an intriguing question, something that few will know the answer to (but should interest all of them). Accept blind guessing for a while before giving the answer to build curiosity. 2.24 Make It Personal Design class activities (or even essays) to address the real lives of the individual students. Instead of asking for reflections on Down’s Syndrome, ask for personal stories of neurological problems by a family member or anyone they have ever met. 2.25 Read Aloud Choose a small text (500 words or less) to read aloud, and ask students to pay particular attention during this phase of lecture. A small text read orally in a larger lecture can focus attention. 2.26 Punctuated Lectures Ask student to perform five steps: listen, stop, reflect, write, give feedback. Students become self-monitoring listeners. 2.27 Word of the Day Select an important term and highlight it throughout the class session, working it into as many concepts as possible. Challenge students to do the same in their interactive activities. 2.28 Recall, Summarize, Question, Connect, and Comment This method of starting each session (or each week) has five steps to reinforce the previous session’s material: recall it, summarize it, phrase a remaining question, connect it to the class as a whole, and comment on that class session. 2.29 Background Knowledge Probe Use questionnaire (multi-choice or short answer) when introducing a new topic. 2.30 Goal Ranking and Matching Students rank their goals for the class, then instructor combines those with her own list. 2.31 Interest/Knowledge/Skills Checklist Assesses interest and preparation for the course, and can help adjust teaching agenda. 2.32 Documented Problem Solutions Keep track of the steps needed to solve specific types of problems. Model a list for students first and then ask them to perform similar steps. 2.33 Provocative Picture Begin the lecture with a picture meant to provoke discussion or emotion (another option: a cartoon). "],
["instructor-action-lecture-small-class-size.html", "Chapter 3 Instructor Action: Lecture (Small Class Size) 3.1 Pass the Chalk 3.2 Whiteboard Capture 3.3 Pass the Dart 3.4 Beach Ball Bingo 3.5 Bingo Balls of Doom 3.6 Town Hall Meeting 3.7 The Half Class Lecture 3.8 Tournament 3.9 Three Part Interview", " Chapter 3 Instructor Action: Lecture (Small Class Size) 3.1 Pass the Chalk Provide chalk or a soft toy; whoever has it must answer your next question, and they pass it on to the student of their choice. 3.2 Whiteboard Capture Using a smartphone, take photographs of the whiteboard at the end of the day and post them to Canvas (labeled by date) for easy student reference. 3.3 Pass the Dart Like Pass the Chalk, use a real (but safe?) dartboard to decide which student must answer the next question (student names are arranged on the dartboard already). 3.4 Beach Ball Bingo Write questions or prompts onto all surfaces of a beach ball (or tape them on). When the next student catches the ball, he/she answers one of the questions where fingers are touching the ball. 3.5 Bingo Balls of Doom Every student is assigned a number; when the faculty member pulls that number from the bingo cage, that student has to answer the next question. 3.6 Town Hall Meeting Abdicate the front of the room for a student willing to speak out on a controversial subject, and when she is done with her comment, she selects the next speaker from the hands raised. 3.7 The Half Class Lecture Divide the class in half and provide reading material to one half. Lecture on that same material to the other half of the class. Then, switch the groups and repeat, ending with a recap by pairing up members of opposite groups. 3.8 Tournament Divide the class into at least two groups and announce a competition for most points on a practice test. Let them study a topic together and then give that quiz, tallying points. After each round, let them study the next topic before quizzing again. The points should be carried over from round to round. The student impulse for competition will focus their engagement onto the material itself. 3.9 Three Part Interview Pose the following question to the entire class: “What do you think are the three biggest issues related to ____.” Choose the student with the birthday closest to today’s date and have them stand and share their 3 responses to the question for one minute. Move clockwise around the room until all have shared. "],
["student-action-individual.html", "Chapter 4 Student Action Individual 4.1 Mind Dump 4.2 One-Minute Papers 4.3 Backchannel Discussion 4.4 Muddiest Point 4.5 Misconception Check 4.6 Drawing for Understanding 4.7 Snowballs 4.8 Focused Listing 4.9 Focused Listing by Letter 4.10 Gallery Walk 4.11 Activity Gallery Walk 4.12 Turn Taking Reading 4.13 Haiku 4.14 Whip Around 4.15 Rotating Chair 4.16 Media Break 4.17 Photo Homework 4.18 Board of Artwork 4.19 Time Traveler 4.20 Circle the Questions 4.21 Ask the Winner 4.22 What’s the Principle 4.23 Video Selfie 4.24 Infographic 4.25 Bookmark Notes 4.26 True or False? 4.27 “Real-World” 4.28 Concept Mapping 4.29 Advice Letter 4.30 Tabloid Titles 4.31 Bumper Stickers 4.32 One-Sentence Summary 4.33 Directed Paraphrasing 4.34 Word Journal 4.35 Truth Statements 4.36 Objective Check 4.37 Opposites 4.38 Student Storytelling 4.39 Application to Major 4.40 Pro and Con Grid 4.41 Harvesting 4.42 Chain Notes 4.43 Focused Autobiographical Sketches 4.44 Course-Related Self-Confidence Surveys 4.45 Profiles of Admirable Individuals 4.46 Memory Matrix 4.47 Categorizing Grid 4.48 Defining Features Matrix 4.49 What/How/Why Outlines 4.50 Approximate Analogies 4.51 Problem Recognition Tasks 4.52 Switch it up! 4.53 Reading Rating Sheets 4.54 Assignment Assessments 4.55 Exam Evaluations 4.56 Group-Work Evaluations 4.57 Teacher-Designed Feedback Forms 4.58 Writing Fables", " Chapter 4 Student Action Individual Many of these can be used as partnerwork or groupwork instead; or may escalate to that after some individual effort. 4.1 Mind Dump Students write for five minutes on last night’s reading, and this paper gets collected. The entire chapter’s worth of mind dumps are returned as a surprise to help students study for the test. 4.2 One-Minute Papers Students write for one minute on a specific question (which might be generalized to “what was the most important thing you learned today”). Best used at the end of the class session. 4.3 Backchannel Discussion While the instructor presents, students use digital devices to engage in a chatroom-style conversation projected alongside the instructor. Students ask questions, make comments, and share relevant resources. The instructor periodically ties the conversation into their presentation. 4.4 Muddiest Point Like the Minute Paper, but asks for the “most confusing” point instead. Best used at the end of the class session. 4.5 Misconception Check Discover class’s preconceptions. Useful for starting new chapters. 4.6 Drawing for Understanding Students illustrate an abstract concept or idea. Comparing drawings around the room can clear up misconceptions. 4.7 Snowballs Ball up several blank pieces of paper and throw them around the room. Each time a “snowball” lands on a desk, the recipient must write three takeaways from today’s (or yesterday’s) class, taking care not to duplicate other ideas already on this paper, and then throw it onward. After nine ideas are on each page, pause for students to debrief the pages in groups. 4.8 Focused Listing Students list several ideas related to the main focus point (example: list all the possible causes of the Civil War). Helpful for starting new topics, such as a brainstorm. 4.9 Focused Listing by Letter Same as “focused listing” but students are restricted to start each term in their list with just one letter announced by the teacher (ie, “all answers must start with an S”). 4.10 Gallery Walk Stations or displays are spread across the room, and students go around to each station individually or in groups, completing a task or responding to a prompt at each station. 4.11 Activity Gallery Walk Stations around the room have activities, rather than materials to read/debrief/discuss, each of which take a significant amount of time to work through. Students usually choose to work on problems they have the most trouble with, and skip ones they already understand. 4.12 Turn Taking Reading Instead of the instructor reading a paragraph on screen (or leaving silence for students to do it), instruct them we will sit in silence until someone is moved to read ONE sentence, then someone else anyone will start the next sentence. Adds “good” tension and raises energy. 4.13 Haiku Students write a haiku (a three-line poem: 5-syllables, then 7, then 5) on a given topic or concept, and then share it with others. 4.14 Whip Around Give students a few seconds to think of their answer to a question, then move around the whole class with each one giving their (one word?) answer. Disallow repeat answers (but do allow a “pass” if necessary). 4.15 Rotating Chair One volunteer “takes the microphone” at a time, then calls on the next volunteer. Each subsequent speaker must summarize the previous one’s points (or, if desired, ALL the speakers thus far) before adding original ideas. 4.16 Media Break Designate a two minute break in the middle of class for students to check their electronic devices, with the understanding they won’t use them otherwise in the entire class period. 4.17 Photo Homework Students are assigned to use a smartphone to snap a picture of something at home (or out in the city) that captures a specific concept from the class, as assigned by the teacher. 4.18 Board of Artwork Post publicly the collected drawings / abstract concepts that students turned in for a previous activity and create an opportunity for discussion and debrief. 4.19 Time Traveler Students video themselves at the start of the semester answering questions similar to the eventual final exam, then critique it near the end of the term. 4.20 Circle the Questions Pre-make a handout that has a few dozen likely student questions (make them specific) on your topic for that day and ask students to circle the ones they don’t know the answers to, then turn in the paper. 4.21 Ask the Winner Ask students to silently solve a problem on the board. After revealing the answer, instruct those who got it right to raise their hands (and keep them raised); then, all other students are to talk to someone with a raised hand to better understand the question and how to solve it next time. 4.22 What’s the Principle After recognizing the problem, students assess what principle to apply in order to solve it. Helps focus on problem TYPES rather than individual specific problems. Principle(s) should be listed out. 4.23 Video Selfie Ask students to make a video of themselves performing the homework (or lab), as they will take it more seriously and be more likely to avoid mistakes. 4.24 Infographic Students use online services (visual.ly, infogr.am) to create an infographic that combines flowchart logic and visual presentation 4.25 Bookmark Notes Distribute full-length paper to be used as a bookmark for the current chapter. On it, record prompts and other “reading questions”, and require students to record their notes, observations, and objections while reading onto these bookmarks for collection and discussion in class. 4.26 True or False? Distribute index cards (one to each student) on which is written a statement. Half of the cards will contain statements that are true, half false. Students decide if theirs is one of the true statements or not, using whatever means they desire. Variation: designate half the room a space for those who think their statements are true, and the other half for false. 4.27 “Real-World” Have students discuss in class how a topic or concept relates to a real- world application or product. Then have students write about this topic for homework. Variation: ask them to record their answer on index cards. 4.28 Concept Mapping Students write keywords onto sticky notes and then organize them into a flowchart. Could be less structured: students simply draw the connections they make between concepts. 4.29 Advice Letter Students write a letter of advice to future students on how to be successful students in that course. 4.30 Tabloid Titles Ask students to write a tabloid-style headline that would illustrate the concept currently being discussed. Share and choose the best. 4.31 Bumper Stickers Ask students to write a slogan-like bumper sticker to illustrate a particular concept from lecture. Variation: can be used to ask them to sum up the entire course in one sentence. 4.32 One-Sentence Summary Summarize the topic into one sentence that incorporates all of who/what/when/where/why/how creatively. 4.33 Directed Paraphrasing Students asked to paraphrase part of a lesson for a specific audience (and a specific purpose). 4.34 Word Journal First, summarize the entire topic on paper with a single word. Then use a paragraph to explain your word choice. 4.35 Truth Statements Either to introduce a topic or check comprehension, ask individuals to list out “It is true that…” statements on the topic being discussed. The ensuing discussion might illustrate how ambiguous knowledge is sometimes. 4.36 Objective Check Students write a brief essay in which they evaluate to what extent their work fulfills an assignment’s objectives. 4.37 Opposites Instructor lists out one or more concepts, for which students must come up with an antonym, and then defend their choice. 4.38 Student Storytelling Students are given assignments that make use of a given concept in relation to something that seems personally relevant (such as requiring the topic to be someone in their family). 4.39 Application to Major During last 15 minutes of class, ask students to write a short article about how the point applies to their major. 4.40 Pro and Con Grid Students list out the pros and cons for a given subject. 4.41 Harvesting After an experience/activity in class, ask students to reflect on “what” they learned, “so what” (why is it important and what are the implications), and “now what” (how to apply it or do things differently). 4.42 Chain Notes Instructor pre-distributes index cards and passes around an envelope, on which is written a question relating to the learning environment (i.e., are the group discussions useful?) Students write a very brief answer, drop in their own card, and pass the envelope to the next student. 4.43 Focused Autobiographical Sketches Focuses on a single successful learning experience, one relevant to the current course. 4.44 Course-Related Self-Confidence Surveys Simple questions that measure how self-confident students are when it comes to a specific skill. Once they become aware they can do it, they focus on it more. 4.45 Profiles of Admirable Individuals Students write a brief profile of an individual in a field related to the course. Students assess their own values and learn best practices for this field. 4.46 Memory Matrix Identify a key taxonomy and then design a grid that represents those interrelationships. Keep it simple at first. Avoid trivial or ambiguous relationships, which tend to backfire by focusing students on superficial kinds of learning. Although probably most useful in introductory courses, this technique can also be used to help develop basic study skills for students who plan to continue in the field 4.47 Categorizing Grid Hand out rectangles divided into cells and a jumbled listing of terms that need to be categorized by row and column. 4.48 Defining Features Matrix Hand out a simple table where students decide if a defining feature is PRESENT or ABSENT. For instance, they might have to read through several descriptions of theories and decide if each refers to behaviorist or constructivist models of learning. 4.49 What/How/Why Outlines Write brief notes answering the what / how / why questions when analyzing a message or text. 4.50 Approximate Analogies Students provide the second half of an analogy (A is to B as X is to Y). 4.51 Problem Recognition Tasks Offer case studies with different types of problems and ask students to identify the TYPE of problem (which is different from solving it) 4.52 Switch it up! Ask students to work on one problem for a few minutes and intentionally move to a second problem without debriefing the first one, then solve the second one and only then return to the first one for more work. A carefully chosen second problem can shed light on the first problem, but this also works well if the problems are not directly related to each other. 4.53 Reading Rating Sheets Students fill out a ratings sheet on the course readings, on how clear, useful, and interesting it was. 4.54 Assignment Assessments Students give feedback on their homework assignments, and evaluate them as learning tools. 4.55 Exam Evaluations Students explain what they are learning from exams, and evaluate the fairness, usefulness, and quality of tests. 4.56 Group-Work Evaluations Questionnaires asking how effective groupwork has been in the class. 4.57 Teacher-Designed Feedback Forms Rather than use standardized evaluation forms, teachers create ones tailored for their needs and their classes. Especially useful midway through the term. 4.58 Writing Fables Students write an animal fable (or at least sketch its outline) that will lead to a one-sentence moral matching the current concept discussed in class. May be done verbally instead. "],
["student-action-pairs.html", "Chapter 5 Student Action: Pairs 5.1 Think-Pair-Share 5.2 Pair-Share-Repeat 5.3 Teach-OK 5.4 Wisdom of Another 5.5 Human Flashcards 5.6 Storytelling Gaps 5.7 Do-Si-Do 5.8 Forced Debate 5.9 Optimist/Pessimist 5.10 Teacher and Student 5.11 Peer Review Writing Task 5.12 Invented Dialogues 5.13 My Christmas Gift 5.14 Psychoanalysis 5.15 Get One, Give One", " Chapter 5 Student Action: Pairs 5.1 Think-Pair-Share Students share and compare possible answers to a question with a partner before addressing the larger class. 5.2 Pair-Share-Repeat After a pair-share experience, ask students to find a new partner and debrief the wisdom of the old partnership to this new partner. 5.3 Teach-OK The instructor briefly explains a concept. The teacher then says “teach!”, and the students respond “OK!”. Students then form pairs and take turns re-teaching the concept to one another. 5.4 Wisdom of Another After any individual brainstorm or creative activity, partner students up to share their results. Then, call for volunteers of students who found their partner’s work to be interesting or exemplary. Students are sometimes more willing to share in plenary the work of fellow students than their own work. 5.5 Human Flashcards Students take turns calling out terms they were expected to memorize, and demand an answer from their partner. 5.6 Storytelling Gaps One partner relay a story that summarizes learning in the chapter so far, but leaves out crucial fine information (such as dates that should have been memorized). The partner listens and records dates silently on paper as the story progresses and then updates the first person. 5.7 Do-Si-Do Students do partner work first, then sound off by twos. All of the 2’s stand up and find a new partner (the 1’s are seated and raise their hands until a new partner comes), then debrief what was said with the first partner. Variation: Later, all the 1’s come together in a large circle for a group debrief, while the 2’s have their own circle. 5.8 Forced Debate Students debate in pairs, defending either their preferred position or the opposite of their preferred position. Variation: Half the class takes one position, half the other. The two halves line up, face each other, and debate. Each student may only speak once, so that all students on both sides can engage the issue. 5.9 Optimist/Pessimist In pairs, students take opposite emotional sides of a conversation. This technique can be applied to case studies and problem solving as well. 5.10 Teacher and Student Individually brainstorm the main points of the last homework, then assign roles of teacher and student to pairs. The teacher’s job is to sketch the main points, while the student’s job is to cross off points on his list as they are mentioned, but come up with 2-3 ones missed by the teacher. 5.11 Peer Review Writing Task To assist students with a writing assignments, encourage them to exchange drafts with a partner. The partner reads the essay and writes a three- paragraph response: the first paragraph outlines the strengths of the essay, the second paragraph discusses the essay’s problems, and the third paragraph is a description of what the partner would focus on in revision, if it were her essay. 5.12 Invented Dialogues Students weave together real quotes from primary sources, or invent ones to fit the speaker and context. 5.13 My Christmas Gift Students mentally select one of their recent gifts as related to or emblematic of a concept given in class, and must tell their partners how this gift relates to the concept. The one with a closer connection wins. 5.14 Psychoanalysis Students get into pairs and interview one another about a recent learning unit. The focus, however, is upon analysis of the material rather than rote memorization. Sample Interview Questions: Can you describe to me the topic that you would like to analyze today? What were your attitudes/beliefs before this topic? How did your attitudes/beliefs change after learning about this topic? How will/have your actions/decisions altered based on your learning of this topic? How have your perceptions of others/events changed? 5.15 Get One, Give One Students fold a piece of paper in half and write “Give One” on one side and “Get One” on the other side. On the “Give One” side, as them to write four insights from today’s material. Have them stand up and find a partner. Each student shares one idea from their “Give One” side of the paper and writes down one idea on the “Get One” side of the paper. Find a new partner until your “Get One” side of paper is full of new ideas! "],
["student-action-groups.html", "Chapter 6 Student Action: Groups 6.1 Jigsaw (Group Experts) 6.2 Single Jigsaw 6.3 Carousel Brainstorming 6.4 World Café 6.5 Mystery Numbers 6.6 Assembling Strips 6.7 Empty Table 6.8 Group Symbols 6.9 With a Creative Twist 6.10 Gap Exercise 6.11 Brain Drain 6.12 Interactive Lit Review 6.13 Balloon Pop 6.14 Things You Know 6.15 Board Rotation 6.16 Make it a Story 6.17 Creating Categories 6.18 Pass the Problem 6.19 Pick the Winner 6.20 Layered Cake Discussion 6.21 Claymation Videos 6.22 Student Learning Communities 6.23 Lecture Reaction 6.24 Movie Application 6.25 Student Pictures 6.26 Definitions and Applications 6.27 TV Commercial 6.28 Blender 6.29 Human Tableau or Class Modeling 6.30 Build From Restricted Components 6.31 Ranking Alternatives 6.32 Simulation 6.33 Group Instructional Feedback Technique 6.34 Classroom Assessment Quality Circles 6.35 Audio and Videotaped Protocols 6.36 Imaginary Show and Tell 6.37 Six Degrees of “RNA Transcription Errors” 6.38 Sticky Note Discussions 6.39 Pinwheel Discussions 6.40 Snowball Discussions", " Chapter 6 Student Action: Groups 6.1 Jigsaw (Group Experts) Give each group a different topic. Re-mix groups with one planted “expert” on each topic, who now has to teach his new group. Also useful to have them teach each other sections of the syllabus on the first day. 6.2 Single Jigsaw Divide the class in two. After speed sharing or similar activity, each person finds a partner from the other group to do a lengthy debrief. 6.3 Carousel Brainstorming Everyone in the group writes out a problem statement, then passes the paper to the student on the left. This student records one possible answer or idea. At the signal, all papers shift to the left again, until the entire circle has seen each paper and they return to their original owners. 6.4 World Café Small groups tackle the same driving question; plenary debrief, then everyone except table hosts find a new table (new groups) for a second discussion question. The host leads discussions and draws ideas between rounds, taking notes for sticky wall posters. 6.5 Mystery Numbers Every student in the group gets a unique number (such as 1-5), but the teacher doesn’t announce until AFTER the discussion period which person (number) is going to report back to the larger class. This will convince everyone to participate fully. 6.6 Assembling Strips Give each group an envelope with cut-out strips that assemble into a timeline, a plan of action, etc. Option: include “too many” so groups have to be selective. 6.7 Empty Table Hand each group a blank table with headers in place for rows and columns, but interior cells are blank until the group fills them in (example: column headers could be different authors such as Shakespeare, Goethe, etc, and row headers could be genres such as poems, novels, essays, etc) 6.8 Group Symbols Ask students in groups to come up with a summary (or thesis statement) of the reading on a scrap of paper, then add a handwritten symbol or stick figure drawing to identify the scrap. Pass to the right, pausing at each group, until everyone has seen everything. Using the symbols as identification, each group decide which two statements are the best, and record the votes on the board. 6.9 With a Creative Twist When assigning group presentations of different topics, each group also gets a ‘twist’ at random (such as must deliver some lines as limericks, must present part as karaoke song, etc) 6.10 Gap Exercise Students freewrite for five minutes on “what is” versus “what should be” (or some other gap in your field) then debrief in threes. When it’s a student’s turn, she first summarizes her freewrite and then is silent and listens as the other two ask questions only (give no advice, do not swap stories), then work around the group every couple of minutes. 6.11 Brain Drain Divide students into groups of 5 or 6. Hand out an empty grid of six rows and three columns to every student. Provide a prompt or task at the top to brainstorm. Each person brainstorms possible answers in row one. After three minutes, rotate papers clockwise and work on row 2 (but do not repeat any answers from row 1). Continue until sheet is filled in, then debrief to find the best answers. 6.12 Interactive Lit Review Give a different snippet of reading to each group in the room and a specific task (such as “map ideas onto this larger set of principles you see on the screen”); capture bullets onto the board, then follow with a Gallery Walk to lead to more debrief. 6.13 Balloon Pop Give each group an inflated balloon with the task/problem trapped inside on a piece of paper. At the signal, all groups pop their balloons. Injects fun, noise, and energy to a group assignment. 6.14 Things You Know Give an envelope to every student. Inside are cut-up strips of paper with the topics/principles they should know about already. They divide into two piles: things they know well, and things they need help with. Then they debrief with nearby students on things any of them need help with. 6.15 Board Rotation Assign groups of students to each of the boards you have set up in the room (four or more works best), and assign one topic/question per board. After each group writes an answer, they rotate to the next board and write their answer below the first, and so on around the room. Variations: pass around flipchart paper with the same task, or use the idea of “table topics” where the topic stays at one table while students rotate. Consider using Google Docs for common note-taking at each table. 6.16 Make it a Story Encourage students to submit their group projects as a comic or story created online (bubblr, StripCreator, StoryJumper, or Storify) 6.17 Creating Categories In groups, students freewrite a position statement about your topic. Then they sort quotes/claims on strips of paper that you handed out, by creating categories as they go. Finally, they add their position statements on (or between) categories. The exercise should point out “families” of assumptions about a topic. 6.18 Pass the Problem Divide students into groups. Give the first group a case or a problem and ask them to identify (and write down) the first step in solving the problem or analyzing the case (3 minutes). Pass the problem on to the next group and have them identify the next step. Continue until all groups have contributed. 6.19 Pick the Winner Divide the class into groups and have all groups work on the same problem and record an answer/strategy on paper. Then, ask groups to switch with a nearby group, and evaluate their answer. After a few minutes, allow each set of groups to merge and ask them to select the better answer from the two choices, which will be presented to the class as a whole. 6.20 Layered Cake Discussion Every table/group works on the same task for a few minutes, then there’s a plenary debrief for the whole class, and finally repeat with a new topic to be discussed in the groups. 6.21 Claymation Videos Instead of a written paper or essay, the deliverable of a group project can be a video uploaded to YouTube created by the group using modeling clay and a stop-motion video app on their smartphones. 6.22 Student Learning Communities Like faculty learning communities, these communities of practice are meant to invest the participants with ownership and a focus on sharing and joint discovery. Can be structured or unstructured. 6.23 Lecture Reaction Divide the class into four groups after a lecture: questioners (must ask two questions related to the material), example givers (provide applications), divergent thinkers (must disagree with some points of the lecture), and agreers (explain which points they agreed with or found helpful). After discussion, brief the whole class. 6.24 Movie Application In groups, students discuss examples of movies that made use of a concept or event discussed in class, trying to identify at least one way the movie-makers got it right, and one way they got it wrong. 6.25 Student Pictures Ask students to bring their own pictures from home to illustrate a specific concept to their working groups. 6.26 Definitions and Applications In groups, students provide definitions, associations, and applications of concepts discussed in lecture. 6.27 TV Commercial In groups, students create a 30-second TV commercial for the subject currently being discussed in class. Variation: ask them to act out their commercials. 6.28 Blender Students silently write a definition or brainstorm an idea for several minutes on paper. Then they form into groups, and two of them read their ideas and integrate elements from each. A third student reads his, and again integration occurs with the previous two, until finally everyone in the group has been integrated (or has attempted integration). 6.29 Human Tableau or Class Modeling Groups create living scenes (also of inanimate objects) which relate to the classroom concepts or discussions. 6.30 Build From Restricted Components Provide limited resources (or a discrete list of ideas that must be used) and either literally or figuratively dump them on the table, asking students in groups to construct a solution using only these things (note: may be familiar from the Apollo 13 movie). If possible, provide red herrings, and ask students to construct a solution using the minimum amount of items possible. 6.31 Ranking Alternatives Teacher gives a situation, everyone thinks up as many alternative courses of action (or explanations of the situation) as possible. Compile list. In groups, now rank them by preference. 6.32 Simulation Place the class into a long-term simulation (like as a business) to enable Problem-Based Learning (PBL). 6.33 Group Instructional Feedback Technique Someone other than the teacher polls groups on what works, what doesn’t, and how to fix it, then reports them to the teacher. 6.34 Classroom Assessment Quality Circles A small group of students forms a “committee” on the quality of teaching and learning, which meets regularly and includes the instructor. 6.35 Audio and Videotaped Protocols Taping students while they are solving problems assesses the learner’s awareness of his own thinking. 6.36 Imaginary Show and Tell Students pretend they have brought an object relevant to current discussion, and “display” it to the class while talking about its properties. 6.37 Six Degrees of “RNA Transcription Errors” Like the parlor game “Six Degrees of Kevin Bacon” (in which actors are linked by joint projects), you provide groups with a conceptual start point and challenge them to leap to a given concept in six moves or fewer. One student judge in each group determines if each leap is fair and records the nature of the leaps for reporting back to the class. 6.38 Sticky Note Discussions Divide students into cooperative groups and have them read individually. Ask them to use sticky notes to mark places that they want to talk about in the text. Then direct them to reread as a group and discuss the parts they have marked. 6.39 Pinwheel Discussions Students are divided into groups. All but one of the groups are assigned to specific topics or positions, while the fourth group is designated as the “provocateur” group. Each group chooses a speaker, and speakers sit facing each other with their other group members seated fanned out behind them (the overhead view of this configuration looks like a pinwheel). The speakers discuss their assigned positions (or provoke further discussion, if in the “provocateur” group), and every few minutes, new speakers rotate in and continue the discussion. 6.40 Snowball Discussions Students form pairs and respond to a discussion question posed by the instructor. After a few moments, pairs join together to form groups of 4 and share their ideas. Groups of 4 then join to create groups of 8, and so forth until the entire class is engaged in discussion. "],
["second-chance-testing.html", "Chapter 7 Second Chance Testing 7.1 Déjà vu 7.2 Fake First Grade 7.3 80/20 Rule 7.4 Up to Half 7.5 Group Test / Group Grade 7.6 Group Test / Individual Grade 7.7 Group Second-Test 7.8 Draw Your Partner", " Chapter 7 Second Chance Testing Note: term grading schemes should be adjusted to avoid undue grade inflation 7.1 Déjà vu Let students know the next class period they will be given the IDENTICAL test they just took, and create time for them to discuss in groups what they answered and why. The second test will also be taken by individuals. 7.2 Fake First Grade Give all students 100% on first grade to bolster confidence and appreciation, but also provide what their REAL score would have been, as well as details about how to improve. 7.3 80/20 Rule Students know to expect a second test right after the first one, with 80% of the questions identical, but 20% of the questions different from the first test. 7.4 Up to Half Students have an option to re-take the test, but can only earn extra points that equal 50% of the points missed on the first test (ie, students accrue half-credit on each question answered correctly, if that question was previously missed). 7.5 Group Test / Group Grade Allow students to take an exam as a team, speaking out loud to each other during the exam (but not so loud that other groups can hear them), and they all share the same grade. 7.6 Group Test / Individual Grade Allow students to view and discuss the test as a team, but each student fills out an individual test sheet and thus results are not necessarily the same across the entire group 7.7 Group Second-Test Students take the test individually at first. Then, they take the same test a second time, this time in a group, defending their answers. The individual results should count for more points than the group effort. 7.8 Draw Your Partner All students draw a number, then find a partner with the same number, and pair up to exchange information in the final few minutes of a test. "],
["authorized-cheating-on-in-class-quizzes.html", "Chapter 8 Authorized “Cheating” on In-Class Quizzes 8.1 Free Time with Notes 8.2 Thy Neighbor’s Notes 8.3 Thy Neighbor’s Brain 8.4 No Talking!", " Chapter 8 Authorized “Cheating” on In-Class Quizzes Note: this stresses practice over summative assessment; term grading schemes should be adjusted to avoid undue grade inflation 8.1 Free Time with Notes Near the end of the quizzing period, give the students a specific time frame (e.g., 30 seconds) to glance silently at their own notes—this encourages effective note-taking for the future. 8.2 Thy Neighbor’s Notes Students silently trade notes with a partner and can only use THOSE notes to cheat from (in the final seconds of allowable time). 8.3 Thy Neighbor’s Brain Students are given some precious seconds to talk to each other, usually done WITHOUT allowing them to access notes. Variation: force the conversations to be in whispers only. 8.4 No Talking! Students are given a specific time frame to literally compare answers with neighbors. The catch is, the entire experience must be 100% silent—no talking or noises. Gestures and light touching to gain attention are allowed. "],
["testing-strategies.html", "Chapter 9 Testing Strategies 9.1 Bark/Bite Grading 9.2 Redacted Test 9.3 Test Variants 9.4 Bluffed Test Variants", " Chapter 9 Testing Strategies 9.1 Bark/Bite Grading Collect multiple assessments (such as multiple at-home essay questions at a test) but tell students they will only be graded on ONE of them blindly this will maximize their preparation but minimize the grading workload. 9.2 Redacted Test A few days before the chapter test, deliver to students the ACTUAL test questions to be used, only with key information blacked out (example: “The BLANK law of thermodynamics states that BLANK”). Do not include the multiple choice answers at this stage, which forces students to generate their own effectively tuned study guides. 9.3 Test Variants Testing in large lecture classes with cramped seating can lead to cheating. Creating two versions of the test, and forcing students to alternate while seated in the row, can reduce cheating. Rather than completely different questions, it may be more fair simply to scramble the order in which the (same) questions are delivered across variants. 9.4 Bluffed Test Variants Simply handing out the paper test photocopied onto two different colors, even if using the same questions and the same order, can reduce student cheating. "],
["youtube.html", "Chapter 10 YouTube 10.1 Video Demonstrations 10.2 Student Videos 10.3 Closed Eyes Method 10.4 Interactive Video Quizzes 10.5 Movie Clips 10.6 Embed Into PowerPoint 10.7 Shared Account", " Chapter 10 YouTube 10.1 Video Demonstrations Using a webcam, record a demonstration relevant to your topic and post it to YouTube. 10.2 Student Videos Student projects, presentations, or speeches can take the form of video instead of PowerPoint, and uploaded for the class to see. 10.3 Closed Eyes Method To prevent students at home from “reading” presentations (such as poem recitations) that were supposed to be memorized for YouTube upload, require them to give the performance with their eyes closed. 10.4 Interactive Video Quizzes Using annotations (text boxes) and making them hyperlinks to other uploaded videos, instructors can construct an on-screen “multiple choice” test leading to differentiated video reactions, depending on how the student answers. Requires filming multiple videos and some editing work. 10.5 Movie Clips Show brief segments of popular movies to illustrate a point, start a conversation, have students hunt for what the movie gets wrong, etc. 10.6 Embed Into PowerPoint YouTube videos can be embedded into PPT as long as there is an active Internet connection; save the PPT after recording audio as filetype “Windows Media Video” and upload to YouTube. 10.7 Shared Account Instructor creates a generic YouTube username/account and gives the password to everyone in the class, so student uploads all go to the same place. "],
["twitter.html", "Chapter 11 Twitter 11.1 Report from the Field 11.2 Twitter Clicker Alternative 11.3 Backchannel Conversations in Large Classes 11.4 Follow an Expert 11.5 Tweeted Announcements 11.6 Twitter Pictures and URLs 11.7 Student Summaries 11.8 Historical Tweets 11.9 Quick Contact 11.10 Community-Building 11.11 Twitter Projects 11.12 Brainstorm 11.13 Twitter Poll 11.14 Post Links", " Chapter 11 Twitter 11.1 Report from the Field Students use smart phones to record their observations while witnessing an event/location related to the course of study, capturing more honest and spontaneous reactions 11.2 Twitter Clicker Alternative In large classes, a hashtag can amalgamate all posts by your students in one place, giving them a free-response place to provide feedback or guess at a right answer. Also useful for brainstorming. 11.3 Backchannel Conversations in Large Classes unlike a whispered conversation, a Twitter conversation (searchable by agreed-upon hashtag) becomes a group discussion. Students may also help out other students who missed a brief detail during the lecture. 11.4 Follow an Expert Luminaries in many disciplines, as well as companies and governmental agencies, often publish a Twitter feed. Reading such updates provides a way to stay current. 11.5 Tweeted Announcements Instead of Blackboard, use Twitter to send out announcements like cancelled classes. 11.6 Twitter Pictures and URLs Twitpic and other services allows for photo upload to twitter; bit.ly and other “link shorteners” allow for pasting long URLs as short ones. 11.7 Student Summaries Make one student the “leader” for tweets; she posts the top five important concepts from each session to twitter (one at a time); other students follow her feed and RT for discussion/disagreements 11.8 Historical Tweets Students roleplay as historical figures (Lincoln, Napoleon) or fictional characters (Hamlet, Three Little Pigs) and tweet as if in specific contexts. 11.9 Quick Contact Since sharing cell phone numbers is risky, instructors may wish to let students follow them on Twitter and send Direct Messages that way. 11.10 Community-Building A Twitter group for your specific class creates inclusiveness and belonging. 11.11 Twitter Projects Tweetworks and other apps can enable student groups to communicate with each other more easily. 11.12 Brainstorm Small Twitter assignments can yield unexpected brainstorming by students, since it’s happening “away” from the LMS. 11.13 Twitter Poll PollDaddy and other apps enable Twitter to gather interest, information, attitudes, and guesses. 11.14 Post Links News stories and other websites can be linked via Twitter (services such as bit.ly will shorten URLs). "],
["mobile-and-tablet-devices.html", "Chapter 12 Mobile and Tablet Devices 12.1 Compose a Musical Theme 12.2 Create a digital (picture) book", " Chapter 12 Mobile and Tablet Devices 12.1 Compose a Musical Theme Using free apps (like Synth), students create their version of a “theme song” for an academic concept (recidivism, electron shells, etc) and also justify WHY the composition includes the emotion or action it does. 12.2 Create a digital (picture) book Using the camera on their smartphone or tablet, the students take pictures of a topic. This could be areas or people that matter to them (if you use it as an ice-breaker activity) or any other topic. Using the Book Creator app which can be used on the iPad as an app or online on their laptop or Android device, the create a short digital (picture) book with texts explaining what is shown in the pictures. "],
["clickers-student-responses-and-alternatives.html", "Chapter 13 Clickers, Student Responses, and Alternatives 13.1 Handheld Clicker 13.2 Cloud-Based Clicker Alternatives 13.3 PollEverywhere 13.4 Sli.do 13.5 Hand Held Response Cards 13.6 Plickers 13.7 Color Boards 13.8 Fingers on Chest 13.9 Assertion Agreement", " Chapter 13 Clickers, Student Responses, and Alternatives 13.1 Handheld Clicker External vendors provide hardware (receivers) to faculty for free, and students buy a handheld device (usually $20) and maybe also online access by semester. Vendors include iClicker, CPS, and Turningpoint 13.2 Cloud-Based Clicker Alternatives External vendors that use a website to track student input data using their own devices (laptop, smartphone, etc) and the campus wi- fi. Vendors charge students per semester (usually $20); there is no hardware for faculty members. Examples include LearningAnalytics, Top Hat Monocle, and Via Response. 13.3 PollEverywhere Cloud-based clicker alternative that uses cell phone texting (SMS) for student responses. Business model calls for faculty-centered payment by user, but the free option suffices for anonymous polling of up to 35 students. 13.4 Sli.do Like PollEverywhere, Sli.do is a website that allows for free polls; in this case, up to 1,000 participants (but the free version is limited to three questions). 13.5 Hand Held Response Cards Distribute (or ask students to create) standardized cards that can be held aloft as visual responses to instructor questions. Example: hand- write a giant letter on each card to use in multiple choice questions. 13.6 Plickers free handheld response cards for download (https://www.plickers.com/) that get scanned by teacher’s smartphone, even at a distance, to “collect” results. 13.7 Color Boards Students are issued (or create their own) a set of four paper-sized cards. These can be used to vote on questions raised in class by lifting the appropriate board into the air. Optionally, the back of each card should be white so students do not see what others have answered. 13.8 Fingers on Chest Students vote on multiple choice questions by showing a finger count (1 through 4). Rather than raise them into the air, they hold their fingers across their chests so other students don’t see what the majority is voting. 13.9 Assertion Agreement Pose an assertion at the start of class that students vote on agreement; then revisit the same question after the class lecture/discussion has explored the concept more deeply. "],
["creating-groups.html", "Chapter 14 Creating Groups 14.1 Quick Division 14.2 Question and Answer Cards 14.3 Telescoping Images 14.4 Speed Sharing 14.5 Trio Rotation 14.6 Go to Your Post 14.7 Four Corners 14.8 Deck of Cards 14.9 Everyone Point!", " Chapter 14 Creating Groups 14.1 Quick Division Divide your class into two roughly equal segments for simultaneous, parallel tasks by invoking their date of birth: “if your birthday falls on an odd-numbered day, do task X…if your birthday is even, do task Y.” Other variations include males and females, months of birth, odd or even inches in their height (5’10” vs 5’11”). 14.2 Question and Answer Cards Make index cards for every student in the class; half with questions about class content; half with the right answers. Shuffle the cards and have students find their appropriate partner by comparing questions and answers on their own cards. 14.3 Telescoping Images When you need the class to form new groups, craft sets of index cards that will be grouped together by theme, and randomly pass them out for students to seek the other members of their new groups. Example: one set of four index cards has pictures of Europe on a map, then France, then the Eiffel Tower, then a person wearing a beret (thematically, the images “telescope” from far away to close up, and the students must find others in their particular set of telescoping images). 14.4 Speed Sharing Students write definitions, concepts, quiz questions, etc. on index cards and form two concentric circles, facing each other. For thirty seconds (or 60), they share their knowledge with the person opposite them. Then, the outer circle “rotates” so that everyone has a new partner, and the sharing is repeated. This can be done until each student has completed the circuit. 14.5 Trio Rotation Group students into threes, and arrange the groups into a large circle. Each team of three works on a problem. Then, each team assigns a 1, 2, and 3 number to each person. The 1’s stay put, but the 2’s rotate clockwise and the 3’s rotate counterclockwise. Newly formed teams then work on a new problem. 14.6 Go to Your Post Tape a sign onto opposite sides of the walls with different preferences (different authors, skills, a specific kind of problem to solve, different values) and let students self-select their working group 14.7 Four Corners Put up a different topic in each corner of the room and ask students to pick one, write their ideas about it down, then head to “their” corner and discuss opinions with others who also chose this topic. 14.8 Deck of Cards Use playing cards to form groups by suit (clubs, hearts, etc), by card (kinds, jacks), or by number. You can pre-assign roles by card. 14.9 Everyone Point! On a count of three, everyone point to someone in the group. Winner gets to decide who does the debrief to the plenary class. "],
["icebreakers.html", "Chapter 15 Icebreakers 15.1 Building a Company 15.2 Something in Common 15.3 Describe in Three Words 15.4 Introduce Your Partner’s Non-Obvious Trait 15.5 Scrapbook Selection 15.6 Brush with Fame 15.7 Name Game 15.8 Human Bingo 15.9 Line Dance 15.10 Two Truths and a Lie 15.11 Name Tag Trio 15.12 Sketch Intro 15.13 Speed Skating 15.14 Word Association Cloud 15.15 Answer Any Three 15.16 Family Name Game 15.17 What’s in a Name? 15.18 Line Up 15.19 Wheel in a Wheel 15.20 Scavenger Hunt 15.21 Course Expectation Exercise", " Chapter 15 Icebreakers 15.1 Building a Company In groups, students catalog their various strengths, talents, and skills onto a single sheet. Then, they invent a company/business that makes use of at least one item from everyone in the group. Share with the larger group. 15.2 Something in Common Place students in pairs and tell them to share with each other until they figure out something they both have in common (even though it’s just a bluff); then ask each partnership to share the common item with the room at large. 15.3 Describe in Three Words Ask students to learn about their partner, then use only three words in the plenary debrief to describe that person. 15.4 Introduce Your Partner’s Non-Obvious Trait Students partner up and are tasked with learning one thing about the other person that is not obvious by looking at them. Then, they introduce their partner to the larger class. Instructors can use this time to record a crude seating chart of the students and begin to learn their names. 15.5 Scrapbook Selection Put students in groups and give each group a big pile of printed photos (best if laminated maybe different shapes/sizes?) Ask them to choose one as a group that epitomizes their reaction/definition of the topic being discussed, and explain why. 15.6 Brush with Fame Students relate their closest encounter with someone famous, even if it has to be a story about something that happened to a friend or relative. 15.7 Name Game Students form circles in groups of 8-10 and one at a time state their name with an alliterative action: “I’m Jumping James!” Optimally, they should perform the action as well. They proceed around the circle, stating names and performing the actions, adding names one at a time, until the last person in the circle will have to say everyone’s name and perform all the actions. 15.8 Human Bingo Students become acquainted at the start of a semester by performing a scavenger hunt you design as a handout: “find someone who dislikes carrots, someone who owns a German car, someone who has read a book about submarines, etc.” 15.9 Line Dance Students line up according to their level of agreement on a controversial subject: strong agreement on one side, strong disagreement on the other. 15.10 Two Truths and a Lie Go around the room and ask each student to relate two true statements and one falsehood about themselves, without giving away which is false. 15.11 Name Tag Trio Color code name tags and ask people to form groups of three made up of people with nametags of the same color, then introduce themselves. 15.12 Sketch Intro Ask participants to draw a picture, using no letters, that captures a key facet of their experience, philosophy, or personality. 15.13 Speed Skating Like the Olympic sport that moves in a circle rapidly, line up students in a circle and step forward one at a time to say a quick personal statement (I am Belgian, I am allergic to peanuts, I love classical music) and then step back into position. 15.14 Word Association Cloud Collect secret-ballot responses to a word association prompt related to your topic, and paste them into a word-cloud generator to create an image that shows which words were used the most. 15.15 Answer Any Three Write 5 questions on the board and ask students to stand (or pair off) and answer any 3 of the 5 questions posed. Some sample questions might include: “I have always wanted to……, The person I most admire is…, The two most important job responsibilities I have are ________ and ________., I’m a sucker for…, One reason why I entered my field is…, Something few people know about me is…” Content-related questions may also be used to review material being presented. 15.16 Family Name Game To help students (and you!) get to know students’ names, ask them to share some history about their name including: 1) who named them, 2) how was the decision for their name made, 3) are they a namesake and do they know that person, 4) do they like their name, 5) have they ever gone by a different name, 6) do they have a nickname, etc. 15.17 What’s in a Name? Pair students up and allow them to interview one another about their first and middle names, noting any cultural uniqueness. Then have each student in the dyad introduce their partner to the rest of the class sharing what they learned about their partner’s name(s). 15.18 Line Up Ask students to arrange themselves in a line according to measure of some characteristic (i.e., height, age, birthdate, level of athleticism, etc.). To add a twist, ask students to complete this task without talking. 15.19 Wheel in a Wheel Ask half of the class form a circle facing outward. Then have the other half of the class form a circle around those students, facing inward, so that they are facing one of the students in the inner circle. The inner circle remains seated throughout the exercise, while the outer circle rotates to the right, one person at a time. With each new pairing you provide a discussion topic/question that will help the students get to know one another. Make sure both partners have time to share. Some example topics include: What do you consider to be one of your greatest accomplishments in life? What person has most affected your life in a positive way? What are the best aspects of your personality and why? 15.20 Scavenger Hunt Ask students to circulate around the room and locate classmates who fit in certain categories (i.e., only children, lived abroad, bi- or multi-lingual, same major, etc. You can also include statements that revolve around class content. 15.21 Course Expectation Exercise Write the name of your course on the blackboard. Ask students to individually write down three expectations they have for you or for the course. Then put students into small groups and tell them they must reach consensus regarding their group’s top 3-5 expectations. Then allow groups to report back to the whole class. "],
["games-useful-for-review.html", "Chapter 16 Games (Useful for Review) 16.1 Crossword Puzzle 16.2 Jeopardy 16.3 Bingo 16.4 Pictionary 16.5 Super-Password 16.6 Guess the Password 16.7 Twenty Questions 16.8 Hollywood Squares 16.9 Scrabble 16.10 Who am I? 16.11 Ticket out the Door", " Chapter 16 Games (Useful for Review) 16.1 Crossword Puzzle Create a crossword puzzle as a handout for students to review terms, definitions, or concepts before a test. Some online websites will automate the puzzle creation. 16.2 Jeopardy Play jeopardy like the TV show with your students. Requires a fair amount of preparation (see quizboxes.com for a simpler way). Can be used also for icebreakers (such as finding out what participants already know about your subject, your university, etc). 16.3 Bingo Fill out various answers onto bingo cards (each with different words and ordering), then have students cross off each as the definition is read verbally. The first with a whole row or column wins. 16.4 Pictionary For important concepts and especially terms, have students play pictionary: one draws images only, the rest must guess the term. 16.5 Super-Password Also for concepts and terms; one student tries to get his partner to say the key term by circumlocution, and cannot say any of the “forbidden words” on a card prepared ahead of time. 16.6 Guess the Password The instructor reveals a list of words (esp. nouns) one at a time and at each point, ask students to guess what key term they are related to. The hints become increasingly specific to make the answer more clear. 16.7 Twenty Questions Assign a person, theory, concept, event, etc to individual students and have the partner ask yes/no questions to guess what the concept is. Also works on a plenary level, with one student fielding the questions from the whole class. 16.8 Hollywood Squares Choose students to sit as “celebrities” at the front of the class. Variation: allow the celebrities to use books and notes in deciding how to help the contestants. 16.9 Scrabble Use the chapter (or course) title as the pool of letters from which to make words (e.g., mitochondrialdna) and allow teams to brainstorm as many words as possible from that list, but all words must be relevant to this test. Variation: actually play scrabble on boards afterward. 16.10 Who am I? Tape a term or name on the back of each student, out of view. Each student then wanders about the room, posing yes/no questions to the other students in an effort to guess the term on his own back. 16.11 Ticket out the Door At the end of class, ask students to summarize the lecture today, or provide one new personal significant learning outcome (in 3-5 sentences), and give their response to the professor for their ticket out of the door. "],
["interaction-through-homework.html", "Chapter 17 Interaction Through Homework 17.1 Find the Company 17.2 Diagnostic Learning Logs 17.3 Process Analysis 17.4 Productive Study-Time Logs 17.5 Double-Entry Journals 17.6 Paper or Project Prospectus 17.7 Annotated Portfolios 17.8 Student Questions (Index Cards) 17.9 Student Questions (Group-Decided) 17.10 Questions as Homework 17.11 Student-Generated Test Questions 17.12 Minute Paper Shuffle", " Chapter 17 Interaction Through Homework 17.1 Find the Company Students search the Internet for a corporation that makes use of concepts/ideas from class, and must defend their choice in the next class session. 17.2 Diagnostic Learning Logs Students track main points in lecture and a second list of unclear points. They then reflect on and analyze the information and diagnose their weaknesses. 17.3 Process Analysis Students track the steps they take to finish an assignment and comment on their approaches to it. 17.4 Productive Study-Time Logs Short records students keep on how long they study for a class; comparison allows those with lesser commitment to see the disparity. 17.5 Double-Entry Journals Students note first the important ideas from reading, and then respond personally. 17.6 Paper or Project Prospectus Write a structured plan for a term paper or large project. 17.7 Annotated Portfolios Student turns in creative work, with student’s explanation of the work in relation to the course content and goals. ## Student Questions 17.8 Student Questions (Index Cards) At the start of the semester, pass out index cards and ask each student to write a question about the class and your expectations. The cards rotate through the room, with each student adding a check-mark if they agree this question is important for them. The teacher learns what the class is most anxious about. 17.9 Student Questions (Group-Decided) Stop class, group students into fours, ask them to take five minutes to decide on the one question they think is crucial for you to answer right now. 17.10 Questions as Homework Students write questions before class on 3x5 cards: “What I really wanted to know about mitochondrial DNA but was afraid to ask…” 17.11 Student-Generated Test Questions Students create likely exam questions and model the answers. Variation: same activity, but with students in teams, taking each others’ quizzes. 17.12 Minute Paper Shuffle Ask students to write a relevant question about the material, using no more than a minute, and collect them all. Shuffle and re-distribute, asking each student to answer his new question. Can be continued a second or third round with the same questions. "],
["role-play.html", "Chapter 18 Role-Play 18.1 Role-Playing 18.2 Role Reversal 18.3 Jury Trial 18.4 Press Conference 18.5 Press Conference (Guest Speaker) 18.6 Analytic Memo", " Chapter 18 Role-Play 18.1 Role-Playing Assign roles for a concept, students research their parts at home, and they act it out in class. Observers critique and ask questions. Can be done with one student or multiple students participating in the role-play. 18.2 Role Reversal Teacher role-plays as the student, asking questions about the content. The students are collectively the teacher, and must answer the questions. Works well as test review/prep. 18.3 Jury Trial Divide the class into various roles (including witnesses, jury, judge, lawyers, defendant, prosecution, audience) to deliberate on a controversial subject. 18.4 Press Conference Ask students to role-play as investigative reporters asking questions of you, the expert on the topic. They should seek a point of contradiction or inadequate evidence, hounding you in the process with follow-up questions to all your replies. Variation: can be done as group activity, with students first brainstorming questions to ask. 18.5 Press Conference (Guest Speaker) Invite a guest speaker and run the class like a press conference, with a few prepared remarks and then fielding questions from the audience. 18.6 Analytic Memo Write a one-page analysis of an issue, roleplaying as an employer or client. "],
["student-presentations.html", "Chapter 19 Student Presentations 19.1 Fishbowl 19.2 Forced Rhyming 19.3 Impromptu Speeches 19.4 Anonymous Peer Feedback 19.5 PowerPoint Presentations 19.6 Shower Boards", " Chapter 19 Student Presentations 19.1 Fishbowl A student unpacks her ideas and thoughts on a topic in front of others, who take notes and then write a response. Avoid asking questions. Variation: Two students have a discussion in front of the class, while others take notes and write a response. 19.2 Forced Rhyming As students provide individual elements of a group presentation, they can be asked to take on artificial limitations to engage their creativity. One member must rhyme each line in couplets, for instance, or another must speak only in nouns. 19.3 Impromptu Speeches Students generate keywords, drop them into a hat, and self- choose presenters to speak for 30 seconds on each topic. 19.4 Anonymous Peer Feedback For student presentations or group projects, encourage frank feedback from the observing students by asking them to rip up a page into quarters and dedicating comments to each presenter. Multiple variations are possible in “forcing” particular types of comments (i.e., require two compliments and two instances of constructive feedback). Then, ask students to create a pile of comments for Student X, another pile for Student Y, and so on. 19.5 PowerPoint Presentations For those teaching in computer-mediated environments, put students into groups of three or four students. Students focus their attention on a chapter or article and present this material to the class using PowerPoint. Have groups conference with you beforehand to outline their presentation strategy and ensure coverage of the material. 19.6 Shower Boards Purchase a slab of shower board from a home improvement store for under $20 and have them cut it into four parts. Use these four boards as whiteboards in student groups; they bring the boards to the front to offer their presentations. "],
["brainstorming.html", "Chapter 20 Brainstorming 20.1 Group Concept Mapping 20.2 Affinity Grouping 20.3 Round Robin 20.4 Brainstorming on the Board 20.5 Brainstorming Tree 20.6 Brainstorming in a Circle 20.7 Chalk Talk", " Chapter 20 Brainstorming 20.1 Group Concept Mapping Start with large posterboards on tables around the room, each with only a central node on it. Participants move around the room, adding sub- nodes to each poster until they are full. 20.2 Affinity Grouping Each student writes one idea per sticky note, making their own pile. Then, student place the notes onto the whiteboard, attempting to group similar ideas near each other. 20.3 Round Robin Have groups silently list top 3 answers to a problem/question. Allow all groups to present one idea in a round robin format until all groups have exhausted their lists. Scribe all answers and then discuss how to reduce/re-categorize answers. Have groups vote on top three, provide results, discuss, and vote again. 20.4 Brainstorming on the Board Students call out concepts and terms related to a topic about to be introduced; the instructor writes them on the board. If possible, group them into categories as you record the responses. Works to gauge pre-existing knowledge and focus attention on the subject. 20.5 Brainstorming Tree While brainstorming on the board, circle the major concepts and perform sub-brainstorms on those specific words; the result will look like a tree blooming outward. 20.6 Brainstorming in a Circle Group students to discuss an issue together, and then spend a few minutes jotting down individual notes. One person starts a brainstorming list and passes it to the student to the right, who then adds to the list and passes it along again. 20.7 Chalk Talk Ask students to go to multiple boards around the room to brainstorm answers to a prompt/assignment, but disallow all talking. Can also be done in groups. "],
["online-interaction.html", "Chapter 21 Online Interaction 21.1 Online Chat (All-Day) 21.2 Online Chat (Quick) 21.3 Online Evaluation 21.4 Pre-Class Writing 21.5 E-Mail Feedback", " Chapter 21 Online Interaction 21.1 Online Chat (All-Day) For classes meeting at least partially in an online environment, instructors can simulate the benefits gained by a chat-room discussion (more participation from reserved instructors) without requiring everyone to meet in a chat room for a specific length of time. The day begins with a post from the instructor in a discussion board forum. Students respond to the prompt, and continue to check back all day, reading their peers’ posts and responding multiple times throughout the day to extend discussion. 21.2 Online Chat (Quick) To gauge a quick response to a topic or reading assignment, post a question, and then allow students to chat in a synchronous environment for the next 10 minutes on the topic. A quick examination of the chat transcript will reveal a multitude of opinions and directions for further discussion. In online environments, many students can “talk” at once, with less chaotic and more productive results than in a face-to-face environment. 21.3 Online Evaluation For those teaching in online environments, schedule a time which students can log on anonymously and provide feedback about the course and your teaching. Understand, however, that anonymity online sometimes breeds a more aggressive response than anonymity in print. 21.4 Pre-Class Writing A few days before your computer-mediated class begins, have students respond in an asynchronous environment to a prompt about this week’s topic. Each student should post their response and at least one question for further discussion. During the face-to-face meeting, the instructor can address some of these questions or areas not addressed in the asynchronous forum. 21.5 E-Mail Feedback Instructor poses questions about his teaching via e-mail; students reply anonymously. "],
["credits.html", "Chapter 22 Credits", " Chapter 22 Credits Kevin Yee | drkevinyee@gmail.com | Last updated 3/10/2019 Creative Commons BY-NC-SA-OK to use and remix if non-commercial, must credit me and use same CC license. (No need to email for permission as long as this footer is included in your copy). Many individuals have assisted over the years by contributing ideas from their own teaching practices. They are listed below in alphabetical order: Melody Bowdon Oana Cimpean Tace Crouse Kenyon Daniel Sara Friedman Gail Grabowsky Jace Hargis Amanda Helip-Wooley Vicki Lavendol Eric Main Emad Mansour Lianna McGowan Sommer Mitchell Alison Morrison-Shetlar Christina Partin Kingsley Reeves Kenyatta Rivers Erin Saitta Anna Turner Nicole West The ebook version is maintained by Sharon Klinkenberg. Any issues or suggestions can be directed at him. Or if you are bold, you can even fork the repository and edit the document through github. "],
["references.html", "Chapter 23 References", " Chapter 23 References Angelo, Thomas/K. Patricia Cross. Classroom Assessment Techniques. 2nd Edition. San Francisco: Jossey-Bass, 1993. Gonzalez, Jennifer. “The Big List of Class Discussion Strategies.” Cult of Pedagogy, 15 Oct. 2015, www.cultofpedagogy.com/speaking-listening-techniques. Morrison-Shetlar, Alison/Mary Marwitz. Teaching Creatively: Ideas in Action. Eden Prairie: Outernet, 2001. McGlynn, Angela. Successful Beginnings for College Teaching. Madison: Atwood, 2001. Silberman, Mel. Active Learning: 101 Strategies to Teach Any Subject. Boston: Allyn and Bacon, 1996. VanGundy, Arthur. 101 Activities for Teaching Creativity and Problem Solving. San Francisco: Pfeiffer, 2005. Watkins, Ryan. 75 e-Learning Activities: Making Online Learning Interactive. San Francisco: Pfeiffer, 2005. "]
]
```

More info:

```r
> packageDescription("bookdown")$GithubSHA1
[1] "31f3197e66cd0ced252dfccf50067ec12f4fabb9"
```

```r
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5      bookdown_0.20.2 later_1.1.0.1   digest_0.6.25  
 [5] mime_0.9        R6_2.4.1        jsonlite_1.7.0  magrittr_1.5   
 [9] evaluate_0.14   rlang_0.4.7     stringi_1.4.6   promises_1.1.1 
[13] rstudioapi_0.11 rmarkdown_2.3   tools_4.0.2     servr_0.17     
[17] stringr_1.4.0   httpuv_1.5.4    xfun_0.16       yaml_2.2.1     
[21] compiler_4.0.2  htmltools_0.5.0 knitr_1.29 
```

**Comment by yihui** [comment]
Sorry, I applied the fix to the wrong code. It should be fixed now.

**Comment by wlandau** [comment]
Works on my end now, thanks Yihui!
